# Funding links for Bitcoin For The Arts, Inc.
# These links appear as a "Sponsor" button on the GitHub repo.

# Custom donation links
custom:
  - https://bitcoinforthearts.org/donate
  - https://bitcoinforthearts.org/donate#bitcoin
